[package]
name = "revise"
version = "0.1.0"
authors = ["Koxiaet <38139193+Koxiaet@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde={ version="1.0.103", features=["derive"] }
serde_json="1.0.44"
regex="1.3.1"
rustyline="5.0.4"
termion="1.5.4"
colored="1.9.0"
rand="0.7.2"
arrayvec="0.5.1"
clap="2.33.0"
