[package]
name = "revise"
version = "0.3.0"
authors = ["Kestrer <kestrer.dev@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
# Data storage
serde = { version = "1.0.116", features = ["derive"] }
ron = "0.6.2"

# Sets and terms
regex = "1.3.9"
rand_regex = "0.14.2"
rand = "0.7.3"

# CLI
clap = "2.33.3"
anyhow = "1.0.32"
directories-next = "1.0.1"

# UI
crossterm = "0.17.7"
scopeguard = "1.1.0"
unicode-width = "0.1.8"
