[package]
name = "revise"
version = "0.2.0"
authors = ["Koxiaet <38139193+Koxiaet@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
regex = "1.3.7"
rustyline = "6.1.1"
crossterm = "0.17.3"
rand = "0.7.3"
arrayvec = "0.5.1"
clap = "2.33.0"
anyhow = "1.0.28"
