[package]
name = "revise"
version = "0.3.0"
authors = ["Koxiaet <38139193+Koxiaet@users.noreply.github.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Data storage
serde = { version = "1.0.110", features = ["derive"] }
ron = "0.6.0"

# Sets and terms
regex = "1.3.7"
rand_regex = "0.14.2"
rand = "0.7.3"

# CLI
clap = "2.33.1"
anyhow = "1.0.31"
directories-next = "1.0.1"

# UI
crossterm = "0.17.5"
scopeguard = "1.1.0"
unicode-width = "0.1.7"
