CREATE EXTENSION pgcrypto;

CREATE TABLE IF NOT EXISTS users (
	id INT8 PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	email TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS cards (
	id INT8 PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	owner INT8 REFERENCES users ON DELETE CASCADE NOT NULL,
	terms TEXT NOT NULL,
	definitions TEXT NOT NULL,
	case_sensitive BOOLEAN NOT NULL,
	knowledge INT2 CHECK(knowledge >= 0 AND knowledge <= 3) NOT NULL,
	safety_net BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS tags (
	id INT8 PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	owner INT8 REFERENCES users ON DELETE CASCADE NOT NULL,
	text TEXT CHECK(text SIMILAR TO E'[^\n]+') NOT NULL,
	description TEXT NOT NULL,
	color BYTEA CHECK(octet_length(color) = 3) NOT NULL -- color of the tag in RGB
);

CREATE TABLE IF NOT EXISTS tagged_cards (
	card INT8 REFERENCES cards ON DELETE CASCADE,
	tag INT8 REFERENCES tags ON DELETE CASCADE,
	PRIMARY KEY (card, tag)
);

CREATE TABLE IF NOT EXISTS tagged_tags (
	tag INT8 REFERENCES tags ON DELETE CASCADE,
	supertag INT8 REFERENCES tags ON DELETE CASCADE CHECK(tag != supertag),
	PRIMARY KEY (tag, supertag)
);

CREATE TABLE IF NOT EXISTS session_cookies (
	cookie_value TEXT PRIMARY KEY,
	for_user INT8 REFERENCES users ON DELETE CASCADE NOT NULL
);
