[package]
name = "revise-database"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
# Used to compute card keys
bincode = "1.3.3"
serde = "1.0.126"

# SQLite is the database used internally
rusqlite = "0.25.3"

thiserror = "1.0.26"

[dev-dependencies]
maplit = "1.0.2"
